- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    pwd: "{{ lookup('env', 'PWD') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - shell
      - gnome
      - zsh
      - tmux
      - nvim
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/nvim.yml
    - include: tasks/git.yml
    - include: tasks/shell_related.yml
    - include: tasks/gnome_related.yml
