- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    pwd: "{{ lookup('env', 'PWD') }}"
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - always
  - name: Ensure local bin directory exists
    file:
      dest: "{{ home }}/.local/bin"
      mode: 0755
      state: directory
    tags:
      - always
  - name: Ensure local lib directory exists
    file:
      dest: "{{ home }}/.local/lib"
      mode: 0755
      state: directory
    tags:
      - always
  - name: Ensure local share directory exists
    file:
      dest: "{{ home }}/.local/share"
      mode: 0755
      state: directory
    tags:
      - always
  tasks:
  - name: Add ssh keys
    import_tasks: tasks/ssh.yml
    tags:
      - base
      - ssh
  - name: Install Zsh and oh-my-zsh
    import_tasks: tasks/zsh.yml
    tags:
      - base
      - zsh
  - name: Install tmux
    import_tasks: tasks/tmux.yml
    tags:
      - base
      - tmux
  - name: Install NeoVim
    import_tasks: tasks/nvim.yml
    tags:
      - base
      - nvim
  - name: Do local git configs
    import_tasks: tasks/git.yml
    tags:
      - base
      - git
  - name: Link scripts
    import_tasks: tasks/scripts.yml
    tags:
      - base
      - scripts
  - name: Install n node version manager
    import_tasks: tasks/nodejs.yml
    tags:
      - base
      - nodejs
  - name: Install Python stuff
    import_tasks: tasks/python.yml
    tags:
      - base
      - python
      - with-extra
      - qmk
  - name: Install Go
    import_tasks: tasks/golang.yml
    tags:
      - base
      - golang
  - name: Install Lazygit
    import_tasks: tasks/apps/lazygit.yml
    tags:
      - with-extra
      - lazygit
  - name: Install Zathura
    import_tasks: tasks/apps/zathura.yml
    tags:
      - with-extra
      - zathura
  - name: Install QMK
    import_tasks: tasks/apps/qmk.yml
    tags:
      - with-extra
      - qmk
  - name: Install misc apt packages
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
      name: [
        "make",  "gawk",  "wget",  "curl",  "ranger",  "htop",  "libfuse2",
        "ripgrep",  "gcc",  "g++",  "unzip",  "neofetch",  "tldr",  "lldb",
        "entr",  "fzf",  "xsel",  "xclip",  "build-essential",  "ansible", 
        "jq"
      ]
    tags:
      - always
  - name: Install misc apt packages (gnome)
    become: true
    tags:
      - with-gnome
    apt:
      force_apt_get: true
      update_cache: true
      state: present
      name: [
        "dconf-editor", "numix-icon-theme-circle", "gnome-tweaks"
      ]
  - name: Install fonts
    import_tasks: tasks/gnome/fonts.yml
    tags:
      - with-gnome
      - fonts
  - name: Install gnome extensions
    import_tasks: tasks/gnome/extensions.yml
    tags:
      - with-gnome
      - gnome-ext
  - name: Set gnome settings
    import_tasks: tasks/gnome/settings.yml
    tags:
      - with-gnome
      - gnome-settings
