- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    pwd: "{{ lookup('env', 'PWD') }}"
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - shell
      - gnome
      - zsh
      - tmux
      - nvim
  - name: Ensure local bin directory exists
    file:
      dest: "{{ home }}/.local/bin"
      mode: 0755
      state: directory
    tags:
      - shell
      - lazygit
  - name: Ensure local lib directory exists
    file:
      dest: "{{ home }}/.local/lib"
      mode: 0755
      state: directory
    tags:
      - shell
  - name: Ensure local share directory exists
    file:
      dest: "{{ home }}/.local/share"
      mode: 0755
      state: directory
    tags:
      - shell
  tasks:
  - name: Add ssh keys
    import_tasks: tasks/ssh.yml
    tags:
      - shell
  - name: Install Zsh and oh-my-zsh
    import_tasks: tasks/zsh.yml
    tags:
      - shell
      - zsh
  - name: Install tmux
    import_tasks: tasks/tmux.yml
    tags:
      - shell
      - tmux
  - name: Install NeoVim
    import_tasks: tasks/nvim.yml
    tags:
      - shell
      - nvim
  - name: Do local git configs
    import_tasks: tasks/git.yml
    tags:
      - shell
  - name: Link scripts
    import_tasks: tasks/scripts.yml
    tags:
      - shell
      - scripts
  - name: Install Lazygit
    import_tasks: tasks/lazygit.yml
    tags:
      - shell
      - lazygit
  - name: Install n node version manager
    import_tasks: tasks/nodejs.yml
    tags:
      - shell
      - nodejs
  - name: All other shell configs
    ansible.builtin.shell: "{{ pwd }}/install-shell.sh"
    tags:
      - shell
    environment:
      PATH: "{{ home }}/.local/share/n/bin:{{ ansible_env.PATH }}"
  - name: All other gnome configs
    ansible.builtin.shell: "{{ pwd }}/install-gnome.sh"
    tags:
      - gnome
