- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    pwd: "{{ lookup('env', 'PWD') }}"
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Ensure local bin directory exists
    file:
      dest: "{{ home }}/.local/bin"
      mode: 0755
      state: directory
    tags:
      - base
      - lazygit
      - ergogen
      - qmk
      - scripts
  - name: Ensure local lib directory exists
    file:
      dest: "{{ home }}/.local/lib"
      mode: 0755
      state: directory
    tags:
      - base
  - name: Ensure local share directory exists
    file:
      dest: "{{ home }}/.local/share"
      mode: 0755
      state: directory
    tags:
      - base
      - nodejs
      - qmk
      - ergogen
  tasks:
  - name: Add ssh keys
    import_tasks: tasks/ssh.yml
    tags:
      - base
      - ssh
  - name: Install Zsh and oh-my-zsh
    import_tasks: tasks/zsh.yml
    tags:
      - base
      - zsh
  - name: Install tmux
    import_tasks: tasks/tmux.yml
    tags:
      - base
      - tmux
  - name: Install NeoVim
    import_tasks: tasks/nvim.yml
    tags:
      - base
      - nvim
  - name: Do local git configs
    import_tasks: tasks/git.yml
    tags:
      - base
      - git
  - name: Link scripts
    import_tasks: tasks/scripts.yml
    tags:
      - base
      - scripts
  - name: Install n node version manager
    import_tasks: tasks/nodejs.yml
    tags:
      - base
      - nodejs
      - ergogen
  - name: Install Lazygit
    import_tasks: tasks/apps/lazygit.yml
    tags:
      - with-extra
      - lazygit
  - name: Install Ergogen
    import_tasks: tasks/apps/ergogen.yml
    tags:
      - with-extra
      - ergogen
  - name: Install QMK
    import_tasks: tasks/apps/qmk.yml
    tags:
      - with-extra
      - qmk
  - name: Install misc dnf packages
    become: true
    dnf:
      state: present
      name: [
        "make",  "gawk",  "wget",  "curl",  "ranger",  "htop",  "fuse-devel",
        "ripgrep",  "gcc",  "g++",  "unzip",  "neofetch",  "tldr",  "lldb",
        "entr",  "fzf",  "xsel",  "xclip",  "python",
        "python3-pip", "python3-virtualenv",  "ansible", "jq"
      ]
    tags:
      - always
  - name: Install misc packages (gnome)
    become: true
    tags:
      - with-gnome
    dnf:
      state: present
      name: [
        "dconf-editor", "numix-icon-theme-circle", "gnome-tweaks"
      ]
  - name: Install fonts
    import_tasks: tasks/gnome/fonts.yml
    tags:
      - with-gnome
      - fonts
  - name: Install gnome extensions
    import_tasks: tasks/gnome/extensions.yml
    tags:
      - with-gnome
      - gnome-ext
  - name: Set gnome settings
    import_tasks: tasks/gnome/settings.yml
    tags:
      - with-gnome
      - gnome-settings
  - name: Fedora post install
    import_tasks: tasks/fedora.yml
    tags:
      - fedora
      - never
