- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    pwd: "{{ lookup('env', 'PWD') }}"
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - shell
      - gnome
      - zsh
      - tmux
      - nvim
  - name: Ensure local bin directory exists
    file:
      dest: "{{ home }}/.local/bin"
      mode: 0755
      state: directory
    tags:
      - shell
      - lazygit
  - name: Ensure local lib directory exists
    file:
      dest: "{{ home }}/.local/lib"
      mode: 0755
      state: directory
    tags:
      - shell
  - name: Ensure local share directory exists
    file:
      dest: "{{ home }}/.local/share"
      mode: 0755
      state: directory
    tags:
      - shell
  tasks:
  - include: tasks/ssh.yml
  - include: tasks/zsh.yml
  - include: tasks/tmux.yml
  - include: tasks/nvim.yml
  - include: tasks/git.yml
  - include: tasks/lazygit.yml
  - include: tasks/shell_related.yml
  - include: tasks/gnome_related.yml
