- name: Ensure local bin directory exists
  file:
    dest: "{{ home }}/.local/bin"
    mode: 0755
    state: directory
  tags:
    - shell
- name: Ensure local lib directory exists
  file:
    dest: "{{ home }}/.local/lib"
    mode: 0755
    state: directory
  tags:
    - shell
- name: Ensure local share directory exists
  file:
    dest: "{{ home }}/.local/share"
    mode: 0755
    state: directory
  tags:
    - shell
