- name: Set Git user name
  ansible.builtin.git_config:
    scope: global
    name: user.name
    value: "Ibrahim Mansoor Khalid"
- name: Set Git user email
  ansible.builtin.git_config:
    scope: global
    name: user.email
    value: "ibrahimmkhalid@gmail.com"
- name: Set Git editor
  ansible.builtin.git_config:
    scope: global
    name: core.editor
    value: "nvim"
- name: Set Git default branch
  ansible.builtin.git_config:
    scope: global
    name: init.defaultBranch
    value: "main"
- name: Unset git configs
  tags:
    - clean
    - never
  git_config:
    scope: global
    name: "{{ item }}"
    state: absent
  with_items:
    - user.name
    - user.email
    - core.editor
    - init.defaultBranch
