- name: "[node version manager] Preparing for n node version manager download"
  tags:
    - clean
  file:
    path: "/tmp/n"
    state: absent
- name: "[node version manager] Ensuring prerequisites"
  become: true
  apt:
    name: make
    state: present
- name: "[node version manager] clone n node version manager"
  ansible.builtin.git:
    repo: "https://github.com/tj/n"
    dest: "/tmp/n"
- name: "[node version manager] Build n node version manager"
  shell: "cd /tmp/n && PREFIX={{ home }}/.local/share/n make install"
- name: "[node version manager] Install lts nodejs version"
  shell: "n lts"
  environment:
    N_PREFIX: "{{ home }}/.local/share/n"
    PATH: "{{ home }}/.local/share/n/bin:{{ ansible_env.PATH }}"
- name: "[node version manager] Uninstall n node version manager"
  tags:
    - clean
    - never
  file:
    path: "{{ home }}/.local/share/n"
    state: absent
