- name: clone n node version manager
  ansible.builtin.git:
    repo: "https://github.com/tj/n"
    dest: "/tmp/n"
- name: Build n node version manager
  shell: "cd /tmp/n && PREFIX={{ home }}/.local/share/n make install"
- name: Install lts nodejs version
  shell: "n lts"
  environment:
    N_PREFIX: "{{ home }}/.local/share/n"
    PATH: "{{ home }}/.local/share/n/bin:{{ ansible_env.PATH }}"
