- name: Preparing nvim
  tags:
    - clean
  file:
    path: "/tmp/nvim"
    state: absent
- name: Install prerequisites
  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl", "make", "build-essential", "gcc", "g++", "fzf", "lldb" ]
- name: Clone nvim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "/tmp/nvim"
    version: stable
- name: Build nvim
  shell: "cd /tmp/nvim && make CMAKE_BUILD_TYPE=Release"
- name: Install nvim
  become: true
  shell: "cd /tmp/nvim && make install"
- name: Create symbolic link for nvim
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: yes
- name: Uninstall nvim
  become: true
  tags:
    - clean
    - never
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home }}/.config/nvim"
    - "{{ lookup('pipe', 'which nvim | xargs dirname') }}"
