- name: "[neovim] Removing/preparing nvim directories"
  tags:
    - clean
  file:
    path: "/tmp/nvim"
    state: absent
- name: "[neovim] Ensure prerequisites for building nvim"
  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl", "make", "build-essential", "gcc", "g++", "fzf", "lldb" ]
- name: "[neovim] Clone nvim"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "/tmp/nvim"
    version: stable
- name: "[neovim] Build nvim"
  shell: "cd /tmp/nvim && make CMAKE_BUILD_TYPE=Release"
- name: "[neovim] Install nvim"
  become: true
  shell: "cd /tmp/nvim && make install"
- name: "[neovim] Create symbolic link for nvim"
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: yes
- name: "[neovim] Uninstall nvim"
  become: true
  tags:
    - clean
    - never
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home }}/.config/nvim"
    - "{{ home }}/.local/share/nvim"
    - "{{ home }}/.local/state/nvim"
    - "{{ lookup('pipe', 'which nvim | xargs dirname') }}"
