- name: "[python] install python3 system wide"
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
    name: ["python3", "python-is-python3", "python3-pip", "python3-venv"]
- name: "[python] download uv python package manager"
  shell: "curl -sSfL https://astral.sh/uv/install.sh | bash"
- name: "[python] Uninstall uv python package manager"
  tags:
    - clean
    - never
  file:
    path: "{{ home }}/.local/bin/uv"
    state: absent
