- name: Get list of scripts
  tags:
    - clean
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/scripts"
    recurse: no
    patterns: "*"
  register: script_files
- name: Create symbolic links for scripts
  ansible.builtin.file:
    src: "{{ playbook_dir }}/scripts/{{ item.path | basename }}"
    dest: "{{ home }}/.local/bin/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ script_files.files }}"
- name: Unlink scripts
  ansible.builtin.file:
    path: "{{ home }}/.local/bin/{{ item.path | basename }}"
    state: absent
  with_items: "{{ script_files.files }}"
  tags:
    - clean
    - never
