- name: "[ssh key config] Ensure .ssh directory exists."
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
- name: "[ssh key config] Install ssh key"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
- name: "[ssh key config] Install ssh public key"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
- name: "[ssh key config] Set authorized key"
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
- name: "[ssh key config] Unset authorized key"
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: absent
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  tags:
    - clean
    - never
- name: "[ssh key config] remove keys"
  file:
    path: "{{ item }}" 
    state: absent
  with_items:
    - "{{ dest_key }}"
    - "{{ dest_key }}.pub"
  tags:
    - clean
    - never
