- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present
- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{  lookup('env', 'USER')  }}/.config/tmux/plugins/tpm"
- name: Create symbolic link for tmux
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/tmux/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"
    state: link
    force: yes
