- name: "[turso db cli] download turso cli installer script"
  shell: 'curl -sSfL https://get.tur.so/install.sh | bash'
  environment:
    TURSO_INSTALL_SKIP_SIGNUP: yes
- name: "[turso db cli] Uninstall turso db cli"
  tags:
    - clean
    - never
  file:
    path: "{{ home }}/.turso"
    state: absent
