- name: Install zsh
  become: true
  apt:
    name: ['zsh', 'curl']
    state: present
- name: Change user's shell to zsh
  become: yes
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ lookup('pipe', 'which zsh') }}"
- name: Remove Oh-my-zsh
  tags:
    - clean
  file:
    path: "{{ home }}/.oh-my-zsh"
    state: absent
- name: Install Oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
- name: Install omz autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
- name: Create symbolic link for .zshrc (dot file management)
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes
