- name: Remove ergogen
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "{{ home }}/.local/share/ergogen"
    - "{{ home }}/.local/bin/ergogen"
- name: Clone ergogen
  ansible.builtin.git:
    repo: 'https://github.com/ergogen/ergogen'
    dest: '{{ home }}/.local/share/ergogen'
- name: Initialize ergogen
  shell: "cd {{ home }}/.local/share/ergogen && npm install"
  environment:
    N_PREFIX: "{{ home }}/.local/share/n"
    PATH: "{{ home }}/.local/share/n/bin:{{ ansible_env.PATH }}"
- name: Install ergogen
  file:
    src: "{{ home }}/.local/share/ergogen/src/cli.js"
    dest: "{{ home }}/.local/bin/ergogen"
    state: link
    force: yes
