- name: "[apps: lazygit] Prepare lazygit directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/lazygit.tar.gz"
    - "/tmp/lazygit"
- name: "[apps: lazygit] Download Lazygit from archive"
  ansible.builtin.get_url:
    url: 'https://github.com/jesseduffield/lazygit/releases/download/v0.50.0/lazygit_0.50.0_Linux_x86_64.tar.gz'
    dest: "/tmp/lazygit.tar.gz"
- name: "[apps: lazygit] Making unarchiving directory"
  file:
    path: /tmp/lazygit
    state: directory
- name: "[apps: lazygit] Unarchiving Lazygit"
  ansible.builtin.unarchive:
    src: "/tmp/lazygit.tar.gz"
    dest: "/tmp/lazygit"
- name: "[apps: lazygit] Installing Lazygit"
  become: true
  copy:
    src: "/tmp/lazygit/lazygit"
    dest: "{{ home }}/.local/bin/lazygit"
    mode: "0777"
- name: "[apps: lazygit] Uninstalling Lazygit"
  become: true
  file:
    path: "{{ home }}/.local/bin/lazygit"
    state: absent
  tags:
    - clean
    - never
