- name: "[apps: qmk] Remove/prepare directories for qmk"
  file:
    path: "{{ home }}/.local/share/qmk_firmware"
    state: absent
  tags:
    - clean
- name: "[apps: qmk] Clone qmk"
  ansible.builtin.git:
    repo: "https://github.com/qmk/qmk_firmware"
    dest: "{{ home }}/.local/share/qmk_firmware"
- name: "[apps: qmk] Install qmk"
  shell: "python3 -m pipx install qmk"
- name: "[apps: qmk] Setup qmk"
  shell: "{{home}}/.local/bin/qmk setup -H {{ home }}/.local/share/qmk_firmware -y"
- name: "[apps: qmk] Uninstall qmk"
  shell: "python3 -m pipx uninstall qmk"
  tags:
    - clean
    - never
