- name: "[apps: zathura] Install zathura from system package manager"
  become: true
  package:
    name: zathura
    state: present
- name: "[apps: zathura] Ensure config directory exists"
  file:
    path: "{{ home }}/.config/zathura"
    mode: 0755
    state: directory
- name: "[apps: zathura] Symlink zathura configuration file"
  file:
    src: "{{ playbook_dir }}/zathurarc"
    dest: "{{ home }}/.config/zathura/zathurarc"
    state: link
    force: yes
- name: "[apps: zathura] Unlink zathura configuration file"
  file:
    path: "{{ home }}/.config/zathura/zathurarc"
    state: absent
  tags:
    - never
    - clean
