#!/bin/bash

tmux rename-window "editor"
tmux send-keys "nvim" C-m

tmux new-window -n "agent"
tmux send-keys "codellm" C-m

tmux new-window -n "runner"
if [ -f "package.json" ]; then
  tmux send-keys "bun run dev" C-m
fi
tmux new-window
tmux select-window -t 1
