#!/bin/bash

file_exists() {
    if [ -e "$1" ]; then
        return 0
    else
        return 1
    fi
}

if file_exists ".todo"; then
    todo_path=$(realpath .todo)
elif git rev-parse --is-inside-work-tree >/dev/null 2>&1 && file_exists "$(git rev-parse --show-toplevel)/.todo"; then
    todo_path=$(realpath "$(git rev-parse --show-toplevel)/.todo")
else
    todo_path="$HOME/.todo"
fi

nvim "$todo_path"
