#! /bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage: mklink [project_name]"
    echo "Creates a symbolic link to the current directory in the sjsu repos directory"
    echo "If no project name is given, the current directory name is used"
    echo "If the project already exists, the script will exit with an error"
    exit 0
fi

if [ -z "$1" ]; then
    basename=$(basename $PWD)
else
    basename=$1
fi

project_dir="$HOME/repos/sjsu/"

if [ -d "$project_dir$basename" ]; then
    echo "Project already exists"
    exit 1
fi

ln -s $PWD $project_dir$basename
