#!/usr/bin/env bash

if [ -n "$1" ]; then
    pdf_path="$1"
else
    find_path="$(realpath "$HOME")"/

    pdf_path=$(find $find_path -name "*.pdf" | fzf)
    if [ -z "$pdf_path" ]; then
      exit 0
    fi
fi

zathura "$pdf_path" --fork 2>/dev/null & disown
