#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$((
      find -L ~/repos -mindepth 1 -maxdepth 2 -type d,l;
      find -L ~/ ~/.config -mindepth 0 -maxdepth 1 -type d,l;
    )| fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

switch_to "$selected_name"
