#!/bin/bash
# Toggle dark mode

## Get the current mode
color_mode_file="$HOME/._.color-mode"
color_mode=$(cat $color_mode_file)

## Check if running on WSL
running_windows=$(uname -a | grep -i "microsoft")

if [[ -n $running_windows ]]; then
  vscode_settings_file=$(wslpath $(wslvar USERPROFILE))/AppData/Roaming/Code/User/settings.json
else
  vscode_settings_file="$HOME/.config/Code/User/settings.json"
fi

## tmux section
if [ $color_mode == "dark" ]; then
  cp ~/.config/tmux/lightmode.conf ~/.config/tmux/colormode.conf
else
  cp ~/.config/tmux/darkmode.conf ~/.config/tmux/colormode.conf
fi
tmux source-file ~/.config/tmux/colormode.conf

## nvim section
if [ $color_mode == "dark" ]; then
  nvim --server /tmp/nvim.pipe --remote-send ":set background=light<CR>"
  nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').setup({background='hard'})<CR>"
else
  nvim --server /tmp/nvim.pipe --remote-send ":set background=dark<CR>"
  nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').setup({background='medium'})<CR>"
fi
nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').load()<CR>"

## vscode section
if [ $color_mode == "dark" ]; then
  sed 's/\("workbench.colorTheme": ".*\)Dark\("\)/\1Light\2/g' $vscode_settings_file -i
else
  sed 's/\("workbench.colorTheme": ".*\)Light\("\)/\1Dark\2/g' $vscode_settings_file -i
fi

if [[ -n $running_windows ]]; then
  ## Windows Terminal section
  settings_file=$(wslpath $(wslvar USERPROFILE))/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
  if [ $color_mode == "dark" ]; then
    sed 's/\("colorScheme": "Everforest \)Dark Medium\("\)/\1Light Hard\2/g' $settings_file -i
    sed 's/\("theme": "\)dark\("\)/\1light\2/g' $settings_file -i
  else
    sed 's/\("colorScheme": "Everforest \)Light Hard\("\)/\1Dark Medium\2/g' $settings_file -i
    sed 's/\("theme": "\)light\("\)/\1dark\2/g' $settings_file -i
  fi
else
  ## gnome-terminal section
  if [ $color_mode == "dark" ]; then
    dconf load /org/gnome/terminal/legacy/profiles:/ < ~/.dotFiles/gnome_specific/gnome-terminal-light.dconf.dump
  else
    dconf load /org/gnome/terminal/legacy/profiles:/ < ~/.dotFiles/gnome_specific/gnome-terminal-dark.dconf.dump
  fi

  ## gnome session section
  if [ $color_mode == "dark" ]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-sage'
    gsettings set org.gnome.gedit.preferences.editor scheme 'Yaru'
    dconf write /org/gnome/shell/extensions/user-theme/name "'Yaru-sage'"
  else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-sage-dark'
    gsettings set org.gnome.gedit.preferences.editor scheme 'Yaru-dark'
    dconf write /org/gnome/shell/extensions/user-theme/name "'Yaru-sage-dark'"
  fi
fi

## Set the new mode
if [ $color_mode == "dark" ]; then
  echo "light" > $color_mode_file
else
  echo "dark" > $color_mode_file
fi
