#!/bin/bash
# Toggle dark mode

## Get the current mode
color_mode_file="$HOME/._.color-mode"
color_mode=$(cat $color_mode_file)

## tmux section
if [ $color_mode == "dark" ]; then
  cp ~/.config/tmux/lightmode.conf ~/.config/tmux/colormode.conf
else
  cp ~/.config/tmux/darkmode.conf ~/.config/tmux/colormode.conf
fi
tmux source-file ~/.config/tmux/colormode.conf

## nvim section
if [ $color_mode == "dark" ]; then
  nvim --server /tmp/nvim.pipe --remote-send ":set background=light<CR>"
  nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').setup({background='hard'})<CR>"
else
  nvim --server /tmp/nvim.pipe --remote-send ":set background=dark<CR>"
  nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').setup({background='medium'})<CR>"
fi
nvim --server /tmp/nvim.pipe --remote-send ":lua require('everforest').load()<CR>"

## Set the new mode
if [ $color_mode == "dark" ]; then
  echo "light" > $color_mode_file
else
  echo "dark" > $color_mode_file
fi
