#!/bin/bash
master=$(xinput list | grep -E "id=.*master.*keyboard" | awk -F'=' '{print $2}' | awk '{print $1}')
integrated=$(xinput list | grep -E "AT Translated Set 2 keyboard.*slave.*keyboard" | awk -F'=' '{print $2}' | awk '{print $1}')
error=0
integratedStatus=1
if [ -z "$integrated" ] # integrated keyboard may be floating
then
    integrated=$(xinput list | grep -E "AT Translated Set 2 keyboard.*floating.*slave" | awk -F'=' '{print $2}' | awk '{print $1}')
    if [ -z "$integrated" ]
    then # integrated keyboard is not found
        error=1
    else # integrated keyboard is floating
        integratedStatus=0
    fi
fi

if [ -z "$master" ]
then
    error=1
fi

if [ $error -eq 0 ]
then
echo "integrated found at: $integrated and status is: $integratedStatus"
echo "master found at: $master"
if (( $integratedStatus == 0 ))
then
    xinput reattach $integrated $master
    echo "reattached integrated"
    notify-send "keyboard Switch" "reattached integrated"
elif (( $integratedStatus == 1 ))
then
    xinput float $integrated
    echo "removed integrated"
    notify-send "keyboard Switch" "removed integrated"
fi
else
echo "There is an error, please check manually"
notify-send "keyboard Switch" "There is an error, please check manually"
fi



