- name: "[gnome extensions] Ensure local gnome extensions directory exists"
  file:
    path: "{{ home }}/.local/share/gnome-shell/extensions"
    mode: 0755
    state: directory
- name: "[gnome extensions] Remove all preinstalled extensions"
  become: true
  ansible.builtin.file:
    path: "/usr/share/gnome-shell/extensions/"
    state: absent
- name: "[gnome extensions] Install user extensions in GNOME"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ToasterUwU/install-gnome-extensions/master/install-gnome-extensions.sh"
    dest: "/tmp/install-gnome-extensions.sh"
    mode: "0777"
- name: "[gnome extensions] Enable GNOME extensions"
  ansible.builtin.shell:
    cmd: "/tmp/install-gnome-extensions.sh --enable --file {{ playbook_dir }}/gnome_specific/extension_links.txt"
- name: "[gnome extensions] Remove installer script"
  file:
    path: "/tmp/install-gnome-extensions.sh"
    state: absent
- name: "[gnome extensions] Remove all extensions"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home }}/.local/share/gnome-shell/extensions"
  tags:
    - clean
    - never
